name: Generate Blog History

on:
  workflow_dispatch:  # Manual trigger
    inputs:
        blog_url:
            description: 'Blog feed URL'
            required: true

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install
        
    - name: Generate Blog History
      run: npm run generate
      env:
        BLOG_URL: ${{ github.event.inputs.blog_url }}
        
    - name: Commit and Push
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add output/blog-history.svg
        git commit -m "Update blog history visualization" || exit 0
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}